name: wehavit
description: A new Havit tracking app without the comparing others.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod_annotation: ^2.3.1
  flutter_riverpod: ^2.4.6
  hooks_riverpod: ^2.4.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  go_router: ^12.1.1
  shared_preferences: ^2.2.2
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.2.0+1
  flutter_hooks: ^0.20.3
  firebase_core: ^2.23.0
  firebase_auth: ^4.13.0
  cloud_firestore: ^4.13.0
  google_sign_in: ^6.1.6
  font_awesome_flutter: ^10.6.0
  equatable: ^2.0.5
  fpdart: ^1.1.0
  uuid: ^4.2.1
  syncfusion_flutter_charts: ^23.1.44
  syncfusion_flutter_gauges: ^23.1.44
  carousel_slider: ^4.2.1
  camera: ^0.10.5+5
  flutter_native_image: ^0.0.6+1
  path: ^1.8.3
  path_provider: ^2.1.1
  firebase_storage: ^11.5.2
  intl: ^0.18.1
  multiselect: ^0.1.0
  image_picker: ^1.0.7
  firebase_messaging: ^14.7.5
  flutter_local_notifications: ^16.2.0
  dotted_border: ^2.1.0
  collection: ^1.18.0
  wheel_chooser: ^1.1.2
  multi_image_picker_plus: ^0.0.4
  fluttertoast: ^8.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  go_router_builder: ^2.3.4
  riverpod_generator: ^2.3.6
  riverpod_lint: ^2.3.4
  custom_lint: ^0.5.6


flutter:
  uses-material-design: true
  assets:
    - assets/images/emoji_3d/
    - assets/logo/
    - assets/fonts/

  fonts:
    - family: SF-Pro
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Thin.otf
          weight: 100
        - asset: assets/fonts/SF-Pro-Text-Ultralight.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Text-Black.otf
          weight: 900

    - family: Giants
      fonts:
        - asset: assets/fonts/Giants-Regular.otf
          weight: 400
        - asset: assets/fonts/Giants-Bold.otf
          weight: 700