import 'package:flutter/material.dart';
import 'package:wehavit/common/constants/constants.dart';

class WehavitTheme {
  static final defaultTheme = ThemeData(
    textTheme: const TextTheme(
      displayLarge: TextStyle(
        fontFamily: 'Giants',
        fontSize: 45.0,
        fontWeight: FontWeight.w400,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      displayMedium: TextStyle(
        fontFamily: 'Giants',
        fontSize: 30.0,
        fontWeight: FontWeight.w400,
        height: 1.8,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      displaySmall: TextStyle(
        fontFamily: 'Giants',
        fontSize: 24.0,
        fontWeight: FontWeight.w700,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      headlineLarge: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 24.0,
        fontWeight: FontWeight.w700,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      headlineMedium: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 22.0,
        fontWeight: FontWeight.w600,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      headlineSmall: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 20.0,
        fontWeight: FontWeight.w600,
        height: 1.2,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      titleLarge: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 24.0,
        fontWeight: FontWeight.w700,
        height: 1.2,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      titleMedium: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 18.0,
        fontWeight: FontWeight.w700,
        height: 1.3,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      titleSmall: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 16.0,
        fontWeight: FontWeight.w600,
        height: 1.25,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      bodyLarge: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 16.0,
        fontWeight: FontWeight.w500,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      bodyMedium: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 14.0,
        fontWeight: FontWeight.w400,
        height: 1.3,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      bodySmall: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 12.0,
        fontWeight: FontWeight.w400,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      labelLarge: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 16.0,
        fontWeight: FontWeight.w800,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      labelMedium: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 12.0,
        fontWeight: FontWeight.w300,
        height: 1.0,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
      labelSmall: TextStyle(
        fontFamily: 'Pretendard',
        fontSize: 11.0,
        fontWeight: FontWeight.w200,
        height: 1.3,
        letterSpacing: 0,
        color: CustomColors.whWhite,
      ),
    ),
  );
}
