// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ZxMvb21D_3Jdf0FzlG8UsmrlL2gDacY',
    appId: '1:764897522660:web:ddd978b027d2fff6b1cdf1',
    messagingSenderId: '764897522660',
    projectId: 'we-havit-be',
    authDomain: 'we-havit-be.firebaseapp.com',
    storageBucket: 'we-havit-be.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5n-Nv6H8SFri1wJBMOeLZ_AXEFq_-Y4',
    appId: '1:764897522660:android:8591da5b662a75acb1cdf1',
    messagingSenderId: '764897522660',
    projectId: 'we-havit-be',
    storageBucket: 'we-havit-be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpEgnUEQs27KjI8pJaypqaTlYzmRkhIa4',
    appId: '1:764897522660:ios:538d4f2955a97d8bb1cdf1',
    messagingSenderId: '764897522660',
    projectId: 'we-havit-be',
    storageBucket: 'we-havit-be.appspot.com',
    iosBundleId: 'com.example.wehavit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpEgnUEQs27KjI8pJaypqaTlYzmRkhIa4',
    appId: '1:764897522660:ios:3f699b0d7e039c91b1cdf1',
    messagingSenderId: '764897522660',
    projectId: 'we-havit-be',
    storageBucket: 'we-havit-be.appspot.com',
    iosBundleId: 'com.example.wehavit.RunnerTests',
  );
}
